#!/usr/bin/env python3
"""Download the web fonts used by the UI into frontend/fonts/ and emit fonts.css.

Self-hosting keeps the portal working on an isolated network where
fonts.googleapis.com is unreachable. Re-run only when the font list changes.

Usage: python3 scripts/fetch_fonts.py
"""
from __future__ import annotations

import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "frontend", "fonts")
CSS_PATH = os.path.join(ROOT, "frontend", "css", "fonts.css")

UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

FAMILIES = [
    "Inter:wght@400;500;600;700;800",
    "Sarabun:wght@400;500;600;700",
    "JetBrains+Mono:wght@400;600",
]
# Only these subsets are needed: the UI is Thai + English.
KEEP_SUBSETS = {"latin", "latin-ext", "thai"}


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    blocks_out: list[str] = []

    for family in FAMILIES:
        url = f"https://fonts.googleapis.com/css2?family={family}&display=swap"
        css = fetch(url).decode("utf-8")
        # each @font-face is preceded by a /* subset */ comment
        parts = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
        for i in range(1, len(parts), 2):
            subset, block = parts[i], parts[i + 1]
            if subset not in KEEP_SUBSETS:
                continue
            m = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", block)
            if not m:
                continue
            font_url = m.group(1)
            fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
            weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
            fname = f"{fam.replace(' ', '')}-{weight}-{subset}.woff2"
            with open(os.path.join(OUT_DIR, fname), "wb") as f:
                f.write(fetch(font_url))
            blocks_out.append(
                block.replace(font_url, f"../fonts/{fname}").strip())
            print(f"  saved {fname}")

    with open(CSS_PATH, "w") as f:
        f.write("/* Self-hosted web fonts — generated by scripts/fetch_fonts.py.\n"
                "   Do not edit by hand; re-run the script instead. */\n")
        f.write("\n".join(blocks_out) + "\n")
    print(f"\nwrote {CSS_PATH} ({len(blocks_out)} @font-face rules)")


if __name__ == "__main__":
    main()
